language: scala
scala:
- 2.11.7
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
env:
  global:
  - secure: n0shGVhtGvg4jA9gQ5Dds7mbczjRjvbjon5RBk0+aXA9EPTGApvk4/zo/LFiCOxfBYPDfe+7EcljgiBFBw9DhggrTtlEKYEAJjqc81B0nZih5H7C9veQcsUWJ6WFEH4HPRSH4kk1PGwmjoDWsk1l6T3jnOblbjcV68pQqA02VBY=
  matrix:
  - SCALAZ_VERSION=7.1.9
  - SCALAZ_VERSION=7.2.4
script: bash bin/travis

